# Generated by Django 2.0.1 on 2018-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdetails',
            name='marksheet_10',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='marksheet_12',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicdetails',
            name='marksheet_clg',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
