# Generated by Django 2.0.1 on 2018-03-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_auto_20180305_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_company',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
