# Generated by Django 2.0.1 on 2018-04-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_auto_20180313_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='contact_number',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
