# Generated by Django 2.0.1 on 2018-02-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company',
            new_name='user',
        ),
    ]
