# Generated by Django 2.0.1 on 2018-02-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180208_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='contact_numbrt',
            new_name='contact_number',
        ),
    ]
