# Generated by Django 2.0.1 on 2018-02-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_contactdetails_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostconnection',
            name='messages',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
