# Generated by Django 2.0.1 on 2018-02-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_userpostconnection_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostconnection',
            name='messages',
        ),
    ]
