# Generated by Django 2.0.1 on 2018-02-13 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_userpostconnection_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField(max_length=500)),
                ('postdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.PostDetails')),
            ],
        ),
    ]
