# Generated by Django 2.0.1 on 2018-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_mesages'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
