# Generated by Django 2.0.1 on 2018-02-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_mesages_is_read'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesages',
            new_name='Messages',
        ),
    ]
