# Generated by Django 2.0.1 on 2018-03-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20180228_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostconnection',
            name='status',
            field=models.CharField(default='Applied', max_length=25),
        ),
    ]
