# Generated by Django 2.0.1 on 2018-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20180308_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetails',
            name='apply_by',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='start_date',
            field=models.DateField(),
        ),
    ]
