# Generated by Django 2.0.1 on 2018-03-13 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20180309_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostconnection',
            name='applied_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 13, 9, 4, 42, 751510)),
        ),
        migrations.AddField(
            model_name='userpostconnection',
            name='stausupdate_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 13, 9, 4, 42, 751540)),
        ),
    ]
