# Generated by Django 2.0.1 on 2018-03-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20180313_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostconnection',
            name='applied_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userpostconnection',
            name='stausupdate_date',
            field=models.DateField(),
        ),
    ]
