# Generated by Django 2.0.1 on 2018-03-13 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20180313_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_date',
            field=models.DateField(default=datetime.date(2018, 3, 13)),
        ),
    ]
