# Generated by Django 2.0.1 on 2018-03-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_messages_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetails',
            name='status',
            field=models.CharField(default='live', max_length=10),
        ),
    ]
