# Generated by Django 2.0.1 on 2018-03-15 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20180314_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_date',
            field=models.DateField(default=datetime.date(2018, 3, 15)),
        ),
    ]
