# Generated by Django 2.0.1 on 2018-03-16 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20180316_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers_HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Answers_intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('is_correct', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProfile')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTestMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date(2018, 3, 16))),
                ('technology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='TestApplicationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Test')),
                ('upc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.UserPostConnection')),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AddField(
            model_name='questiontestmap',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Test'),
        ),
        migrations.AddField(
            model_name='answers_intern',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Question'),
        ),
        migrations.AddField(
            model_name='answers_intern',
            name='upc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.UserPostConnection'),
        ),
        migrations.AddField(
            model_name='answers_hr',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Question'),
        ),
    ]
