# Generated by Django 2.0.1 on 2018-03-20 08:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_auto_20180316_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_date',
            field=models.DateField(default=datetime.date(2018, 3, 20)),
        ),
        migrations.AlterField(
            model_name='test',
            name='creation_date',
            field=models.DateField(default=datetime.date(2018, 3, 20)),
        ),
        migrations.AlterField(
            model_name='test',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Technology'),
        ),
    ]
