# Generated by Django 2.0.1 on 2018-03-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='test',
        ),
        migrations.RemoveField(
            model_name='result',
            name='upc',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
