# Generated by Django 2.0.1 on 2018-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_testapplicationmapping_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapplicationmapping',
            name='result',
            field=models.FloatField(),
        ),
    ]
