# Generated by Django 2.0.1 on 2018-03-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_teststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapplicationmapping',
            name='teststatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.TestStatus'),
        ),
    ]
