# Generated by Django 2.0.1 on 2018-03-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_testapplicationmapping_teststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers_hr',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='answers_intern',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testapplicationmapping',
            name='result',
            field=models.FloatField(default=0),
        ),
    ]
