# Generated by Django 2.0.1 on 2018-03-23 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_auto_20180321_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers_HR',
            new_name='AnswersHR',
        ),
        migrations.RenameModel(
            old_name='Answers_intern',
            new_name='AnswersIntern',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_date',
            field=models.DateField(default=datetime.date(2018, 3, 23)),
        ),
        migrations.AlterField(
            model_name='test',
            name='creation_date',
            field=models.DateField(default=datetime.date(2018, 3, 23)),
        ),
    ]
