# Generated by Django 2.0.1 on 2018-03-27 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_messages_upc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_date',
            field=models.DateField(default=datetime.date(2018, 3, 27)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='upc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.UserPostConnection'),
        ),
        migrations.AlterField(
            model_name='test',
            name='creation_date',
            field=models.DateField(default=datetime.date(2018, 3, 27)),
        ),
    ]
