# Generated by Django 2.0.1 on 2018-04-02 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_auto_20180327_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_date',
            field=models.DateField(default=datetime.date(2018, 4, 2)),
        ),
        migrations.AlterField(
            model_name='test',
            name='creation_date',
            field=models.DateField(default=datetime.date(2018, 4, 2)),
        ),
    ]
