# Generated by Django 2.0.1 on 2018-04-03 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_auto_20180402_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_date',
            field=models.DateField(default=datetime.date(2018, 4, 3)),
        ),
        migrations.AlterField(
            model_name='test',
            name='creation_date',
            field=models.DateField(default=datetime.date(2018, 4, 3)),
        ),
    ]
