# Generated by Django 2.0.1 on 2018-04-09 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_auto_20180403_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_date',
            field=models.DateField(default=datetime.date(2018, 4, 9)),
        ),
        migrations.AlterField(
            model_name='test',
            name='creation_date',
            field=models.DateField(default=datetime.date(2018, 4, 9)),
        ),
    ]
